### Get All Tours
GET http://localhost:3000/api/tours
Content-Type: application/json

###

### Get Tour by ID
GET http://localhost:3000/api/tours/2
Content-Type: application/json

###

### Create a New Tour
POST http://localhost:3000/api/tours
Content-Type: application/json

{
    "category": "Adventure",
    "tourdescription": "watching the whales",
    "duration": "2 hours"
}

###

### Update an Existing Tour
PUT http://localhost:3000/api/tours/11
Content-Type: application/json

{
    "category": "Adventure",
    "tourdescription": "Let's go Hunting! at Maasai Mara @7,000 ksh ",
    "duration": "2 Days"
}

###

### Delete a Tour
DELETE http://localhost:3000/api/tours/3
Content-Type: application/json
