### Register a New User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "john doe",
    "email": "johndoe@gmail.com",
    "password": "rootpassword"
}

###

### Login a User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "rootpassword"
}

###
### Get All Users
GET http://localhost:3000/api/auth/users
Content-Type: application/json

###
### Delete a User
DELETE http://localhost:3000/api/auth/users/1
Content-Type: application/json

###
